---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: matchroutes
  namespace: lmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matchroutes
  template:
    metadata:
      labels:
        app: matchroutes
    spec:
      containers:
        - image: 'harbor.dev.21vianet.com/taojun/matchrouter:latest'
          imagePullPolicy: Always
          name: matchroutes
          ports:
            - containerPort: 8081
              protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: matchroutes-svc2
  namespace: lmanager
spec:
  externalTrafficPolicy: Cluster
  ports:
    - name: http
      nodePort: 31621
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: matchroutes
  type: NodePort