version: '3.8'
services:
  matedb-ui:
    build:
      context: ./
      dockerfile: ./Dockerfile-dev
    image: cmdb/matedb-ui:1.2.0
    volumes:
       - ./web:/usr/share/nginx/html
       - ./nginx.http.dev.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
