{{- range .Values.apps }}
  {{- with . }}
---

apiVersion: v1
kind: Service
metadata: 
  name: {{ .name }}-svc
  labels: 
    app: {{ .name }}-svc
  annotations:
    timestamp: {{ now | quote }}
spec: 
  ports: 
  - port: {{ .port }}
    targetPort: {{ .port }}
    {{- if .nodePort}}
    nodePort: {{ .nodePort}}

    {{- end}}
  type: NodePort
  selector:
    app: {{ .name }}
---
{{- end}}
  {{- end}}
