---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-bak1
  namespace: cmdbv3
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: csi-rbd-sc
---
apiVersion: v1
data:
  bak.sh: >-
    #!/bin/bash

    find /data/bak/ -mindepth 1 -maxdepth 1 -type d -ctime +5 | xargs rm -rf {}
    \; 

    mongodump --host mongo-mongodb-headless --port 27017 --username cc
    --password cc -d cmdb --gzip --out /data/bak/`date +%Y-%m-%d` 

    ls /data/bak/

kind: ConfigMap
metadata:
  name: bakshell
  namespace: cmdbv3


---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: mongodump
  namespace: cmdbv3
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  schedule: '50 12 * * *'
  successfulJobsHistoryLimit: 3
  suspend: false
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: mongodbdump
              image: harbor.dev.21vianet.com/library/mongo:4.4.13-debian-10-r52
              imagePullPolicy: IfNotPresent
              command: ["bash",  "-c", "/shell/bak.sh"]
              volumeMounts:
                - mountPath: /data/
                  name: mongodb-bak1
                - mountPath: /shell/bak.sh
                  name: shell
                  subPath: bak.sh
          restartPolicy: OnFailure
          volumes:
            - name: mongodb-bak1
              persistentVolumeClaim:
                claimName: mongodb-bak1
            - configMap:
                defaultMode: 0777
                name: bakshell
              name: shell