apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lmanager-cmdb-ui.labels" . | nindent 4 }}
data:
  default.conf: |-
{{ .Files.Get "default.conf" | indent 4}}