---
apiVersion: v1
data:
  createUser.js: |
    use cmdb;
    db.createUser({
      user: "cc",
      pwd: "cc",
      roles: [{ role: "readWrite", db: "cmdb" }]
    });

kind: ConfigMap
metadata:
  name: mongocreateuserjs


