apiVersion: v1
kind: Secret
metadata:
  name: metadb-secret
  labels:
    app:  metadb-secret
type: Opaque
stringData:
  redisIp: {{ .Values.env.redisip }}
  redisPass: {{ .Values.env.redispass }}
  mongoIp: {{ .Values.env.mongoip }}
  mongoRootUser: {{ .Values.env.mongorootuser }}
  mongoRootPass: {{ .Values.env.mongorootpass }}
  mongoRootAuthDB: {{ .Values.env.mongorootauthdb }}
  mongoShardNode: {{ .Values.env.mongo_shard_node }}
  mongoCluster: {{ .Values.env.mongo_cluster }}
  mongoPort: "{{ .Values.env.mongoport }}"
  redisPort: "{{ .Values.env.redisport }}"
  redisDBnum: "{{ .Values.env.redisDBnum }}"