apiVersion: v1
kind: Secret
metadata:
  name: metadb-secret
  labels:
    app:  metadb-secret
type: Opaque
stringData:
  redisIp: {{ .Values.env.redisip }}
  redisPass: {{ .Values.env.redispass }}
  mongoIp: {{ .Values.env.mongoip }}
  mongoRootUser: {{ .Values.env.mongorootuser }}
  mongoRootPass: {{ .Values.env.mongorootpass }}
  mongoRootAuthDB: {{ .Values.env.mongorootauthdb}}
  mongoPort: "{{ .Values.env.mongoport }}"
  redisPort: "{{ .Values.env.redisport }}"