{{ $prefix := printf "%s-" .Values.prefix}}
{{- range .Values.apps }}
  {{- with . }}

---
apiVersion: v1
kind: Service
metadata: 
  name: {{ $prefix }}{{ .name }}-svc
  labels: 
    app: {{ $prefix }}{{ .name }}-svc
  annotations:
    timestamp: {{ now | quote }}
spec:
  selector:
    app: {{ $prefix }}{{ .name }}
  {{- if .enable }}
  type: NodePort
  ports:
  - port: {{ .port }}
    targetPort: {{ .port }}
    {{- if .nodePort}}
    nodePort: {{ .nodePort}}
    {{- end}}

  {{- else }}
  type: ClusterIP
  ports:
    - port: {{ .port }}
      targetPort: {{ .port }}
      {{- if .nodePort }}
      nodePort: {{ .nodePort }}
      {{- end }}
  {{- end}}

  {{- end}}
---
{{- end}}
