{{ $prefix := .Values.prefix}}
{{- range .Values.apps }}
  {{- with . }}
  {{- if .enable }}
---
apiVersion: v1
kind: Service
metadata: 
  name: {{ $prefix }}-{{ .name }}-svc
  labels: 
    app: {{ $prefix }}-{{ .name }}-svc
  annotations:
    timestamp: {{ now | quote }}
spec:
  selector:
    app: {{ $prefix }}-{{ .name }}
  type: NodePort
  ports:
  - port: {{ .port }}
    targetPort: {{ .port }}
    {{- if .nodePort}}
    nodePort: {{ .nodePort}}
    {{- end}}
  {{- end}}
  {{- end}}


---
{{- end}}
